# Generated by Django 4.2.5 on 2023-10-30 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_created_task_stress_alter_task_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 4, 55, 31, 99461)),
        ),
    ]
