# Generated by Django 4.2.5 on 2023-10-30 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 5, 6, 2, 570764)),
        ),
        migrations.AlterField(
            model_name='task',
            name='stress',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
