# Generated by Django 4.2.5 on 2023-11-09 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_task_deadline_alter_task_stress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 17, 40, 21, 254221)),
        ),
    ]
